load("@org_pubref_rules_protobuf//protobuf:rules.bzl", "proto_language")

proto_language(
    name = "grpc.js",
    pb_plugin = "//protoc-gen-grpc-js",
    pb_file_extensions = [".grpc.js"],
    visibility = ["//visibility:public"],
)
