package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "protoc-gen-grpc-js",
    srcs = [
        "protoc-gen-grpc-js.cc",
    ],
    deps = [
        "@com_google_protobuf//:protoc_lib"
    ],
)
